matches:
  - trigger: ":ml"
    replace: 'patric.fornasier@gmail.com'

  - trigger: ":cp"
    replace: "commit and push"

  - trigger: ":shrg"
    replace: '¯\_(ツ)_/¯'

  - trigger: ":wu"
    replace: '/wrap-up'

  - trigger: ":clip"
    replace: 'Output your response and also copy it into my clipboard'
